// web/src/components/Upload.tsx
import { useState, useCallback, useRef, useEffect } from 'react';
interface UploadResponse {
  videoId: string;
  uploadUrl: string;
  s3Key: string;
  contentType: string;
}

interface StatusMessage {
  id: string;
  processed: boolean;
  status: string;
}

interface UploadProps {
  onComplete: (videoId: string) => void;
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default function Upload({ onComplete }: UploadProps) {
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [dragging, setDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const eventSourceRef = useRef<EventSource | null>(null);

  // Cleanup SSE on unmount
  useEffect(() => {
    return () => {
      eventSourceRef.current?.close();
    };
  }, []);

  const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected) {
      setFile(selected);
      setErrorMsg('');
    }
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragging(false);
    const dropped = e.dataTransfer.files?.[0];
    if (dropped && dropped.type.startsWith('video/')) {
      setFile(dropped);
      setErrorMsg('');
    } else {
      setErrorMsg('Please drop a video file.');
    }
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragging(false);
  }, []);

  const removeFile = useCallback(() => {
    setFile(null);
    if (inputRef.current) inputRef.current.value = '';
  }, []);

  const connectSSE = useCallback((videoId: string) => {
    const es = new EventSource(`http://localhost:3030/api/v1/status?id=${videoId}`);
    eventSourceRef.current = es;

    es.onmessage = (event: MessageEvent) => {
      try {
        const msg: StatusMessage = JSON.parse(event.data);
        if (msg.processed) {
          setProcessing(false);
          es.close();
          onComplete(videoId);
        }
      } catch (err) {
        console.error('Invalid SSE message:', err);
      }
    };

    es.onerror = () => {
      setErrorMsg('Connection lost. Please refresh and try again.');
      setProcessing(false);
      es.close();
    };
  }, [onComplete]);

  const uploadVideo = useCallback(async () => {
    if (!file) {
      setErrorMsg('Please select a file before uploading.');
      return;
    }

    setUploading(true);
    setErrorMsg('');

    try {
      // Step 1: Get presigned PUT URL
      const presignRes = await fetch(
        `http://localhost:3030/api/v1/upload/presign?filename=${encodeURIComponent(file.name)}`
      );
      if (!presignRes.ok) throw new Error(`Presign failed: ${presignRes.status}`);

      const data: UploadResponse = await presignRes.json();

      // Step 2: Upload file directly to MinIO via presigned URL
      const putRes = await fetch(data.uploadUrl, {
        method: 'PUT',
        headers: { 'Content-Type': data.contentType },
        body: file,
      });
      if (!putRes.ok) throw new Error(`Direct upload failed: ${putRes.status}`);

      // Step 3: Verify upload + enqueue transcode
      const completeRes = await fetch('http://localhost:3030/api/v1/upload', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ videoId: data.videoId, s3Key: data.s3Key }),
      });
      if (!completeRes.ok) {
        const err = await completeRes.json().catch(() => ({}));
        throw new Error(err.error || `Upload verification failed: ${completeRes.status}`);
      }

      setUploading(false);
      setProcessing(true);
      connectSSE(data.videoId);
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : String(err));
      setUploading(false);
    }
  }, [file, connectSSE]);

  // ── Processing State ──
  if (processing) {
    return (
      <div className="upload-card">
        <div className="processing-card">
          <div className="processing-spinner" />
          <h3>Transcoding your video</h3>
          <p>
            Encoding multiple quality levels<span className="processing-dots" />
          </p>
        </div>
      </div>
    );
  }

  // ── Upload State ──
  return (
    <div className="upload-card">
      <div
        className={`drop-zone${dragging ? ' dragging' : ''}`}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        onClick={() => inputRef.current?.click()}
        role="button"
        tabIndex={0}
        aria-label="Drop video file here or click to browse"
      >
        <div className="drop-zone-icon">🎬</div>
        <div className="drop-zone-text">
          <p>
            Drag and drop your video here, or <strong>browse</strong>
          </p>
          <small>Supports all major video formats • Max 100 MB</small>
        </div>
      </div>

      <input
        ref={inputRef}
        id="file-input"
        className="visually-hidden"
        type="file"
        accept="video/*"
        onChange={handleFileChange}
      />

      {file && (
        <div className="file-info">
          <span className="file-info-icon">🎥</span>
          <div className="file-info-details">
            <div className="file-info-name">{file.name}</div>
            <div className="file-info-size">{formatFileSize(file.size)}</div>
          </div>
          <button
            className="file-info-remove"
            onClick={removeFile}
            aria-label="Remove file"
          >
            ✕
          </button>
        </div>
      )}

      {errorMsg && <div className="error-msg">{errorMsg}</div>}

      <button
        className="upload-btn"
        onClick={uploadVideo}
        disabled={!file || uploading}
      >
        {uploading ? (
          <>
            <span className="processing-spinner" style={{ width: 18, height: 18, margin: 0, borderWidth: 2 }} />
            Uploading…
          </>
        ) : (
          <>↑ Upload & Transcode</>
        )}
      </button>
    </div>
  );
}

// web/frontend/src/Upload.svelte
<script lang="ts">
    import { onDestroy } from "svelte";
    import VideoPlayer from "./VideoPlayer.svelte";

    let file: File | null = null;
    let uploading = false;
    let processed = false;
    let videoId: string | null = null;
    let errorMsg = "";
    let eventSource: EventSource | null = null;

    interface UploadResponse {
        videoId: string;
    }

    interface StatusMessage {
        id: string;
        processed: boolean;
        status: string;
    }

    const handleFileChange = (e: Event) => {
        const target = e.target as HTMLInputElement;
        if (target.files && target.files.length > 0) {
            file = target.files[0];
        }
    };

    const uploadVideo = async () => {
        if (!file) {
            errorMsg = "Please select a file before uploading.";
            return;
        }

        uploading = true;
        errorMsg = "";

        try {
            const formData = new FormData();
            formData.append("video", file);

            const res = await fetch("http://localhost:3030/api/v1/upload", {
                method: "POST",
                body: formData,
            });

            if (!res.ok) {
                throw new Error(`Upload failed: ${res.status}`);
            }

            const data: UploadResponse = await res.json();
            videoId = data.videoId;

            connectSSE(videoId);
        } catch (err: unknown) {
            errorMsg = err instanceof Error ? err.message : String(err);
            uploading = false;
        }
    };

    const connectSSE = (id: string) => {
        eventSource = new EventSource(`http://localhost:3030/api/v1/status?id=${id}`);

        eventSource.onmessage = (event: MessageEvent) => {
            try {
                const msg: StatusMessage = JSON.parse(event.data);
                console.log("Message from server:", msg);

                if (msg.processed) {
                    processed = true;
                    uploading = false;
                    eventSource?.close();
                }
            } catch (e) {
                console.error("Invalid SSE message:", e);
            }
        };

        eventSource.onerror = (err: Event) => {
            console.error("SSE error:", err);
            errorMsg = "Connection error. Please refresh the page and try again.";
            eventSource?.close();
        };
    };

    onDestroy(() => {
        eventSource?.close();
    });
</script>

<div class="upload-container">
    {#if !uploading && !processed}
        <input
            id="file-input"
            class="visually-hidden"
            type="file"
            accept="video/*"
            on:change={handleFileChange}
        />
        <label for="file-input" class="btn">Choose File</label>
        <button class="btn primary" on:click={uploadVideo}>Upload</button>
        {#if file}
            <div class="file-name" title={file.name}>{file.name}</div>
        {/if}
    {/if}

    {#if errorMsg}
        <p style="color:red;">{errorMsg}</p>
    {/if}

    {#if uploading && !processed}
        <div class="processing-center">
            <div class="processing-inner">
                <p class="processing-text">Processing video</p>
                <div class="spinner"></div>
            </div>
        </div>
    {/if}

    {#if processed && videoId}
        <div class="player-center">
            <VideoPlayer {videoId} />
        </div>
    {/if}
</div>

<style>
    .upload-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
    }
    .btn {
        padding: 0.5rem 1rem;
        border: 1px solid #d1d5db;
        background: #fff;
        color: #111;
        border-radius: 6px;
        cursor: pointer;
        user-select: none;
    }
    .btn:hover {
        background: #f3f4f6;
    }
    .btn.primary {
        background: #3b82f6;
        color: #fff;
        border-color: #3b82f6;
    }
    .btn.primary:hover {
        background: #2563eb;
        border-color: #2563eb;
    }
    .visually-hidden {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        white-space: nowrap;
        border: 0;
    }
    .processing-center {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 40vh;
        width: 100%;
    }
    .processing-inner {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .processing-text {
        margin-bottom: 0.75rem;
        text-align: center;
    }
    .file-name {
        max-width: 80ch;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        color: #374151;
        font-size: 0.9rem;
    }
    .player-center {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 70vh;
        width: 100%;
    }
    .spinner {
        border: 4px solid #f3f3f3;
        border-top: 4px solid #3b82f6;
        border-radius: 50%;
        width: 36px;
        height: 36px;
        animation: spin 1s linear infinite;
    }
    @keyframes spin {
        to {
            transform: rotate(360deg);
        }
    }
</style>
